#ifndef MAIN_H
#define MAIN_H

//PROGRAMME: 247-637 S-0005
//DESCRIPTION: programme avec service de base de temps par interruptions
//HISTORIQUE:
// 2018-09-24, Yves Roy: cr�ation

//DEFINITIONS REQUISES PAR LE PROGRAMME:


//D�pendances mat�rielles:
#define PILOTEIOAUDIOSELECT_SORTIE 16

#define PILOTEI2CDGPT_SDA 45
#define PILOTEI2CDGPT_SCL 46

#define PILOTEI2CRPI_SDA 35
#define PILOTEI2CRPI_SCL 36
#define PILOTEI2CRPI_NBBYTEARECEVOIR 10

#define PILOTEPWM_LEDG 5
#define PILOTEPWM_LEDR 6
#define PILOTEPWM_LEDW 7
#define PILOTEPWM_LEDB 8

#define INTERFACEDGPT_ADRBASS 0x5800
#define INTERFACEDGPT_ADRMID 0x5880
#define INTERFACEDGPT_ADRTREBLE 0x5A00
#define INTERFACEDGPT_ADRVOLUME 0x5A80

#define INTERFACESOURCE_SELECTRPI 0
#define INTERFACESOURCE_SELECTESP 1

//D�pendances logicielles:

#define SERVICETASKSERVER_PERIODE_EN_US (500L)
#define SERVICEBASEDETEMPS_FREQUENCE_EN_HZ ((1000000L) / SERVICETASKSERVER_PERIODE_EN_US)

#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES 5
#define INTERFACELEDS_PHASE 0
#define INTERFACERPI_PHASE 1
#define INTERFACEDGPT_PHASE 2
#define INTERFACESOURCE_PHASE 3

#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES_DANS_LOOP 1

//INFORMATION PUBLIQUE:
//Definitions publiques:
#define INFORMATION_DISPONIBLE 1
#define INFORMATION_TRAITEE 0
#define REQUETE_ACTIVE 1
#define REQUETE_TRAITEE 0
#define MODULE_EN_FONCTION 1
#define MODULE_PAS_EN_FONCTION 0

//Fonctions publiques:
void neFaitRien(void);

//Variables publiques:
//pas de variables publiques
#endif