#ifndef MAIN_H
#define MAIN_H

//PROGRAMME: 247-637 S-0005
//DESCRIPTION: programme avec service de base de temps par interruptions
//HISTORIQUE:
// 2018-09-24, Yves Roy: cr�ation

//DEFINITIONS REQUISES PAR LE PROGRAMME:


//D�pendances mat�rielles:   
#define PILOTEIOT1_BROCHE 13
#define PILOTEIOB1_BROCHE 14
#define PILOTEIOT1_ETAT_INITIAL_A_ZERO
#define INTERFACEB1_VALEUR_LUE_SI_APPUYE  0   
#define INTERFACEB1_VALEUR_LUE_SI_RELACHE 1
#define INTERFACEB1_DELAI_ANTI_REBOND_EN_MS  15
#define INTERFACET1_VALEUR_POUR_ALLUMER  1   
#define INTERFACET1_VALEUR_POUR_ETEINDRE 0

//D�pendances logicielles:

#define SERVICETASKSERVER_PERIODE_EN_US (500L)
#define SERVICEBASEDETEMPS_FREQUENCE_EN_HZ ((1000000L)/SERVICETASKSERVER_PERIODE_EN_US)

#define INTERFACEB1_FREQUENCE_DES_LECTURES_EN_HZ  100.0
#define INTERFACEB1_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION 10
#define SERVICEPROTOCOLE637_DEBUG //activation de messages de debug

#define SERVICEPROTOCOLE637_FREQUENCE_MAXIMALE_DES_TRANSMISSIONS_EN_HZ 500.0
#define SERVICEPROTOCOLE637_NOMBRE_DE_DONNEES_MAXIMUM  16
#define SERVICEPROTOCOLE637_DEBUT_DE_TRAME  '$'
#define SERVICEPROTOCOLE637_INSERTION 0x00
#define SERVICEPROTOCOLE637_TEMPS_D_ATTENTE_MAXIMAL_EN_MS 4
#define SERVICEPROTOCOLE637_FREQUENCE_MAXIMALE_DES_LECTURES_EN_HZ 2000.0
#define PROCESSUSCLIGNOTANT_TEMPS_ALLUME_EN_MS  500.0
#define PROCESSUSCLIGNOTANT_PERIODE_EN_MS 1000.0

#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES  5
#define INTERFACEB1_PHASE 0
#define SERVICEPROTOCOLE637_PHASE_RECEPTION 1
#define SERVICEPROTOCOLE637_PHASE_TRANSMISSION 4
#define PROCESSUSBOUTONCONNECTE_PHASE 2
#define PROCESSUSCLIGNOTANT_PHASE 3

#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES_DANS_LOOP 1

//INFORMATION PUBLIQUE:
//Definitions publiques:
#define INFORMATION_DISPONIBLE  1
#define INFORMATION_TRAITEE  0
#define REQUETE_ACTIVE  1
#define REQUETE_TRAITEE 0
#define MODULE_EN_FONCTION 1
#define MODULE_PAS_EN_FONCTION 0

//Fonctions publiques:
void neFaitRien(void);

//Variables publiques:
//pas de variables publiques
#endif
